<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to Julian Hyde under one or more contributor license
agreements. See the NOTICE file distributed with this work for
additional information regarding copyright ownership.

Julian Hyde licenses this file to you under the Apache License,
Version 2.0 (the "License"); you may not use this file except in
compliance with the License. You may obtain a copy of the License at:

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- The basics. -->
  <groupId>org.olap4j</groupId>
  <artifactId>parent</artifactId>
  <version>2.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <!-- More project information. -->
  <name>parent</name>
  <description>Open Java API for OLAP</description>
  <url>http://github.com/olap4j/olap4j</url>
  <inceptionYear>2006</inceptionYear>
  <organization>
    <name>olap4j</name>
    <url>http://www.olap4j.org</url>
  </organization>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>julianhyde</id>
      <name>Julian Hyde</name>
      <email>jhyde@apache.org</email>
      <url>https://github.com/julianhyde</url>
      <roles>
        <role>architect</role>
        <role>developer</role>
      </roles>
      <timezone>-8</timezone>
      <properties/>
    </developer>
    <developer>
      <id>lucboudreau</id>
      <name>Luc Boudreau</name>
      <url>https://github.com/lucboudreau</url>
      <roles>
        <role>project manager</role>
        <role>developer</role>
      </roles>
      <timezone>-5</timezone>
      <properties/>
    </developer>
    <developer>
      <id>buggtb</id>
      <name>Tom Barber</name>
      <url>https://github.com/buggtb</url>
      <roles>
        <role>project manager</role>
        <role>developer</role>
      </roles>
      <timezone>0</timezone>
      <properties/>
    </developer>
  </developers>

  <prerequisites>
    <maven>3.6.3</maven>
  </prerequisites>

  <modules>
    <module>api</module>
    <module>tck</module>
    <module>xmla-driver</module>
  </modules>

  <!-- Environment settings. -->
  <scm>
    <connection>scm:git:git://github.com/olap4j/olap4j.git</connection>
    <developerConnection>scm:git:git@github.com:olap4j/olap4j.git</developerConnection>
    <url>https://github.com/olap4j/olap4j/tree/master</url>
  </scm>

  <issueManagement/>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>

    <!-- Dependency and plugin versions (in alphabetical order). -->
    <apache-rat-plugin.version>0.16.1</apache-rat-plugin.version>
    <commons-dbcp2.version>2.12.0</commons-dbcp2.version>
    <foodmart-data-hsqldb.version>0.4</foodmart-data-hsqldb.version>
    <hsqldb.version>2.7.3</hsqldb.version>
    <junit.version>5.11.3</junit.version>
    <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
    <maven-dependency-plugin.version>3.8.1</maven-dependency-plugin.version>
    <maven-javadoc-plugin.version>3.11.1</maven-javadoc-plugin.version>
    <maven-replacer-plugin.version>1.4.1</maven-replacer-plugin.version>
    <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
    <maven-surefire-plugin.version>3.5.2</maven-surefire-plugin.version>
    <!-- A reference implementation of Mondrian for testing.
         Other versions of Mondrian will be able to work on olap4j. -->
    <mondrian.version>4.8.0.0-SAIKU</mondrian.version>
    <ph-javacc-maven-plugin.version>4.1.5</ph-javacc-maven-plugin.version>
    <sortpom-maven-plugin.version>4.0.0</sortpom-maven-plugin.version>
    <build-helper-maven-plugin.version>3.6.0</build-helper-maven-plugin.version>
  </properties>

  <!-- Dependencies. -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.olap4j</groupId>
        <artifactId>olap4j</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.olap4j</groupId>
        <artifactId>olap4j-tck</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.olap4j</groupId>
        <artifactId>olap4j-xmla</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>${junit.version}</version>
      </dependency>
      <dependency>
        <groupId>org.junit.vintage</groupId>
        <artifactId>junit-vintage-engine</artifactId>
        <version>${junit.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-dbcp2</artifactId>
        <version>${commons-dbcp2.version}</version>
      </dependency>
      <dependency>
        <groupId>org.hsqldb</groupId>
        <artifactId>hsqldb</artifactId>
        <version>${hsqldb.version}</version>
      </dependency>
      <dependency>
        <groupId>pentaho</groupId>
        <artifactId>mondrian</artifactId>
        <version>${mondrian.version}</version>
      </dependency>
      <dependency>
        <groupId>net.hydromatic</groupId>
        <artifactId>foodmart-data-hsqldb</artifactId>
        <version>${foodmart-data-hsqldb.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.rat</groupId>
          <artifactId>apache-rat-plugin</artifactId>
          <version>${apache-rat-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${maven-javadoc-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${maven-source-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${build-helper-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>com.github.ekryd.sortpom</groupId>
          <artifactId>sortpom-maven-plugin</artifactId>
          <version>${sortpom-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>com.google.code.maven-replacer-plugin</groupId>
          <artifactId>maven-replacer-plugin</artifactId>
          <version>${maven-replacer-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>com.helger.maven</groupId>
          <artifactId>ph-javacc-maven-plugin</artifactId>
          <version>${ph-javacc-maven-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <excludes>
            <exclude>**/*.md</exclude>
            <exclude>RELEASE_CHECKLIST.txt</exclude>
            <exclude>doc/*</exclude>
            <exclude>.travis.yml</exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.ekryd.sortpom</groupId>
        <artifactId>sortpom-maven-plugin</artifactId>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>sort</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <predefinedSortOrder>default_1_0_0</predefinedSortOrder>
          <keepBlankLines>true</keepBlankLines>
          <expandEmptyElements>false</expandEmptyElements>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${maven-javadoc-plugin.version}</version>
        <configuration>
          <links>
            <link>https://docs.oracle.com/en/java/javase/21/docs/api/</link>
          </links>
        </configuration>
      </plugin>
    </plugins>
  </reporting>
</project>
